name: Patina
options:
  bundleIdPrefix: com.patina
  deploymentTarget:
    macOS: "14.0"
  minimumXcodeGenVersion: "2.38"

settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  Patina:
    type: application
    platform: macOS
    sources:
      - path: Patina
        excludes:
          - "**/*.xcassets"
      - path: ../generated/PatinaCore.swift
    resources:
      - path: Patina/Assets.xcassets
    dependencies:
      - sdk: SystemConfiguration.framework
      - sdk: Security.framework
      - sdk: CoreFoundation.framework
      - sdk: WebKit.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.patina.app
        PRODUCT_NAME: Patina
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Patina
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.news
        INFOPLIST_KEY_NSMainStoryboardFile: ""
        SWIFT_OBJC_BRIDGING_HEADER: $(PROJECT_DIR)/Patina/Patina-Bridging-Header.h
        LIBRARY_SEARCH_PATHS:
          - $(inherited)
          - $(PROJECT_DIR)/../patina-core/target/release
        OTHER_LDFLAGS:
          - $(inherited)
          - -lpatina_core
        HEADER_SEARCH_PATHS:
          - $(inherited)
          - $(PROJECT_DIR)/../generated
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_IDENTITY: "-"
      configs:
        Debug:
          LIBRARY_SEARCH_PATHS:
            - $(inherited)
            - $(PROJECT_DIR)/../patina-core/target/debug
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          LIBRARY_SEARCH_PATHS:
            - $(inherited)
            - $(PROJECT_DIR)/../patina-core/target/release
          SWIFT_OPTIMIZATION_LEVEL: "-O"
    preBuildScripts:
      - name: Build Rust Library
        script: |
          cd "${PROJECT_DIR}/../scripts"
          ./build-rust.sh
        basedOnDependencyAnalysis: false
    entitlements:
      path: Patina/Patina.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-write: true
        com.apple.security.network.client: true

schemes:
  Patina:
    build:
      targets:
        Patina: all
    run:
      config: Debug
    profile:
      config: Release
    archive:
      config: Release
